#!/bin/bash
# 独立音频流方案 - 完整测试指南

echo "========================================================================"
echo "方案2：独立音频流 - 实施完成"
echo "========================================================================"
echo ""
echo "架构说明:"
echo "  C端 ━━━━━━━━━━━━━━> B端 ━━━━━━━━━━━━━━> A端"
echo "   │                    │                    │"
echo "   ├─ 视频 (5558) ────> ├─ 视频 (5557) ────> ├─ 视频显示"
echo "   │                    │                    │"
echo "   └─ 音频 (5559) ────> └─ 音频 (5561) ────> └─ 音频播放"
echo "       独立流              独立转发              独立接收"
echo ""
echo "========================================================================"
echo "修改文件清单"
echo "========================================================================"
echo ""
echo "✅ C_real_video_audio_fixed.py:"
echo "   - 新增: 线程2 (thread_send_audio) - 独立音频发送"
echo "   - 修改: 线程3 (thread_send_data) - 只发送视频"
echo "   - 端口: 5559 (音频专用)"
echo ""
echo "✅ B_reverse_whole_voice.py:"
echo "   - 新增: 线程2 (thread_audio_handler) - 音频转发"
echo "   - 修改: 线程3 (thread_data_handler) - 只处理视频"
echo "   - 端口: 5559 (接收C) → 5561 (发送A)"
echo ""
echo "✅ triple_imu_rs485_publisher_dual_cam_UI_voice.py:"
echo "   - 新增: audio_receiver_thread - 独立音频接收"
echo "   - 修改: video_receiver_thread - 不再接收音频"
echo "   - 新增参数: --audio-host, --audio-port"
echo "   - 端口: 5561 (接收音频)"
echo ""
echo "========================================================================"
echo "测试步骤"
echo "========================================================================"
echo ""
echo "【步骤1】部署 B 端到服务器"
echo ""
echo "cd ~/桌面/WIT_RS485/whole3_2"
echo "./deploy_voice_to_target_server.sh"
echo ""
echo "【步骤2】替换 C 端文件"
echo ""
echo "cd ~/桌面/WIT_RS485/whole3_2"
echo "cp C_real_video_audio.py C_real_video_audio_old_backup.py  # 备份"
echo "cp C_real_video_audio_fixed.py C_real_video_audio.py       # 使用新版本"
echo ""
echo "【步骤3】启动三端（需要3个终端窗口）"
echo ""
echo "终端1 - B 端（服务器）:"
echo "----------------------------------------------------------------------"
echo "./connect.sh  # 建立 SSH 隧道"
echo "cd /data7/yhx/lerobot_data_collection"
echo "./start_b_voice.sh"
echo ""
echo "预期输出:"
echo "[线程1] 命令转发 (A→C)"
echo "[线程2-音频] 启动音频转发服务"
echo "[线程2-音频] 监听 C 音频: *:5559"
echo "[线程2-音频] 转发给 A: *:5561"
echo "[线程3-视频] 处理视频数据流 (C -> B -> A)"
echo ""
echo "终端2 - C 端（本地）:"
echo "----------------------------------------------------------------------"
echo "cd ~/桌面/WIT_RS485/whole3_2"
echo "python C_real_video_audio.py"
echo ""
echo "预期输出:"
echo "[命令线程] 已连接到 B: localhost:5556"
echo "[音频发送线程] 已连接到 B: localhost:5559"
echo "[音频发送线程] 独立音频流已启动"
echo "[数据线程] 摄像头已打开"
echo "[音频回调] Opus 编码器已创建"
echo ""
echo "对着麦克风说话，观察:"
echo "[音频发送线程] 已发送 50 帧, FPS: 16.5, 队列: 2/20"
echo "[视频发送线程] 已发送 20 帧, FPS: 7.9, 视频: 6900B, 音频队列: 2"
echo "                                                       ^^^ 队列不再满"
echo ""
echo "终端3 - A 端（本地）:"
echo "----------------------------------------------------------------------"
echo "cd ~/桌面/WIT_RS485"
echo "python triple_imu_rs485_publisher_dual_cam_UI_voice.py \\"
echo "    --online-only \\"
echo "    --b-host localhost --b-port 5555 \\"
echo "    --enable-video --video-host localhost --video-port 5557 \\"
echo "    --enable-audio --audio-host localhost --audio-port 5561 \\"
echo "    -p /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0 \\"
echo "    --enable-debug --debug-port 5560"
echo ""
echo "预期输出:"
echo "✓ 视频接收已启动: localhost:5557"
echo "✓ 音频接收已启动: localhost:5561 (独立音频流)"
echo "✓ 音频播放已启动: Opus解码 → 扬声器"
echo ""
echo "听到 C 端麦克风的声音，观察:"
echo "🔊 音频接收: 100 帧, 队列: 3/5, 编码: opus"
echo "[音频播放] 已播放 100 帧, FPS: 16.3, 缓冲: 2 帧"
echo ""
echo "========================================================================"
echo "预期效果对比"
echo "========================================================================"
echo ""
echo "修改前（方案1失败的尝试）:"
echo "  C: [音频回调] 队列满，丢弃帧  ← 经常发生"
echo "  C: 音频队列: 5/5               ← 队列总是满"
echo "  A: 播放断断续续                ← 用户体验差"
echo ""
echo "修改后（方案2独立音频流）:"
echo "  C: [音频发送线程] FPS: 16.5    ← 音频独立发送，不受视频限制"
echo "  C: 音频队列: 2/20               ← 队列很空"
echo "  B: [线程2-音频] 已转发 100 帧  ← B 端独立转发"
echo "  A: [音频接收] 100 帧            ← A 端独立接收"
echo "  A: 播放流畅                    ← 用户体验好 ✅"
echo ""
echo "========================================================================"
echo "技术细节"
echo "========================================================================"
echo ""
echo "端口映射:"
echo "  5556: A→C 命令"
echo "  5558: C→B 视频数据"
echo "  5559: C→B 音频数据 ⭐ 新增"
echo "  5557: B→A 视频数据"
echo "  5561: B→A 音频数据 ⭐ 新增"
echo ""
echo "音频流独立的好处:"
echo "  ✅ 音频帧率 16.7fps 不受视频帧率 7.9fps 限制"
echo "  ✅ 音频延迟更低（直接转发，无需等视频帧）"
echo "  ✅ 音频质量更稳定（不会因视频拥塞而丢帧）"
echo "  ✅ 系统解耦，音频和视频互不影响"
echo ""
echo "SSH 隧道命令（别忘了加新端口）:"
echo "  ssh -J root@202.112.113.78:2258 \\"
echo "      -i ./capri_yhx_2237 -p 2237 \\"
echo "      -L 5555:localhost:5555 \\"
echo "      -L 5556:localhost:5556 \\"
echo "      -L 5557:localhost:5557 \\"
echo "      -L 5558:localhost:5558 \\"
echo "      -L 5559:localhost:5559 ⭐ 新增 \\"
echo "      -L 5561:localhost:5561 ⭐ 新增 \\"
echo "      root@202.112.113.74"
echo ""
echo "========================================================================"
echo "故障排查"
echo "========================================================================"
echo ""
echo "如果 C 端音频队列还是满:"
echo "  → 检查音频发送线程是否启动"
echo "  → 查看日志 '[音频发送线程] 已发送 X 帧'"
echo ""
echo "如果 B 端没有音频转发:"
echo "  → 检查 B 端是否有 '[线程2-音频] 已转发 X 帧'"
echo "  → 确认 B 端监听 5559 和 5561 端口"
echo ""
echo "如果 A 端听不到声音:"
echo "  → 检查 A 端是否有 '🔊 音频接收: X 帧'"
echo "  → 确认 A 端连接到 5561 端口"
echo "  → 查看音频播放线程是否有 '[音频播放] 已播放 X 帧'"
echo ""
echo "如果还是断续:"
echo "  → 增大 AUDIO_BUFFER_SIZE (当前5，可以增到10)"
echo "  → 检查网络延迟: ping localhost"
echo "  → 查看系统负载: top"
echo ""
echo "========================================================================"
