#!/bin/bash
# 音频系统测试说明

echo "========================================================================"
echo "音频系统配置更新完成 - 现在使用 48kHz 采样率"
echo "========================================================================"
echo ""
echo "✅ 已更新的文件:"
echo "   - test_audio_loopback.py (48kHz, 2880样本/帧)"
echo "   - C_real_video_audio_fixed.py (48kHz, 2880样本/帧)"
echo "   - triple_imu_rs485_publisher_dual_cam_UI_voice.py (48kHz, 2880样本/帧)"
echo ""
echo "========================================================================"
echo "测试步骤"
echo "========================================================================"
echo ""
echo "【步骤1】测试音频环回（验证硬件和编解码）"
echo "   cd ~/桌面/WIT_RS485/whole3_2"
echo "   python test_audio_loopback.py"
echo ""
echo "   预期结果: 对着麦克风说话，能听到延迟的回声"
echo "   如果听不到: 检查麦克风/扬声器音量设置"
echo ""
echo "【步骤2】替换并测试 C 端"
echo "   cd ~/桌面/WIT_RS485/whole3_2"
echo "   # 备份原文件"
echo "   mv C_real_video_audio.py C_real_video_audio_old.py"
echo "   # 使用修复版"
echo "   mv C_real_video_audio_fixed.py C_real_video_audio.py"
echo "   # 运行 C 端"
echo "   python C_real_video_audio.py"
echo ""
echo "   预期输出: "
echo "   [音频回调] Opus 编码器已创建"
echo "   [音频回调] 已编码 50 帧, PCM: 5760B → Opus: 480B ..."
echo "   [数据线程] 已发送 100 帧, FPS: 7.9, 视频: 5992B, 有音频(累计45) ..."
echo ""
echo "【步骤3】完整系统测试（需要三个终端）"
echo ""
echo "   终端1 - B 端（服务器）:"
echo "   ./connect.sh  # 建立 SSH 隧道"
echo "   cd /data7/yhx/lerobot_data_collection"
echo "   ./start_b_voice.sh  # 使用音频版本"
echo ""
echo "   终端2 - C 端（本地）:"
echo "   cd ~/桌面/WIT_RS485/whole3_2"
echo "   python C_real_video_audio.py"
echo ""
echo "   终端3 - A 端（本地）:"
echo "   cd ~/桌面/WIT_RS485"
echo "   python triple_imu_rs485_publisher_dual_cam_UI_voice.py \\"
echo "       --online-only \\"
echo "       --b-host localhost --b-port 5555 \\"
echo "       --enable-video --video-host localhost --video-port 5557 \\"
echo "       -p /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0 \\"
echo "       --enable-debug --debug-port 5560 \\"
echo "       --enable-audio"
echo ""
echo "   预期结果: A 端能听到 C 端麦克风的声音"
echo ""
echo "========================================================================"
echo "故障排查"
echo "========================================================================"
echo ""
echo "如果 C 端显示 '无音频':"
echo "   1. 检查麦克风音量: alsamixer"
echo "   2. 测试麦克风: arecord -d 3 test.wav && aplay test.wav"
echo "   3. 查看音频设备: python check_audio_devices.py"
echo ""
echo "如果 A 端听不到声音:"
echo "   1. 确认 B 端使用 B_reverse_whole_voice.py"
echo "   2. 确认 A 端有 --enable-audio 参数"
echo "   3. 查看 A 端日志是否显示 '[音频播放] 已播放 X 帧'"
echo ""
echo "如果有 'input overflow' 警告:"
echo "   这是正常的，表示音频采集速度略快，不影响功能"
echo ""
echo "========================================================================"
